DROP TABLE `supawdb`.`userAddress`;
DROP TABLE `supawdb`.`inCategory`;
DROP TABLE `supawdb`.`address`;
DROP TABLE `supawdb`.`category`;
DROP TABLE `supawdb`.`purchase`;
DROP TABLE `supawdb`.`review`;
DROP TABLE `supawdb`.`cart`;
DROP TABLE `supawdb`.`user`;
DROP TABLE `supawdb`.`product`;